- extism.go
- extism_test.go
- runtime.go
- Removes `GuestRuntime.Cleanup` and `GuestRuntime.InitOnce`
- Calls GuestRuntime.Init once for the lifetime of a Plugin
- Improves Haskell reactor support
See: https://github.com/extism/extism/pull/411
> refactor: Simplify runtime initialization

- extism.go
- extism_test.go
- host.go
- runtime.go
I wanted to change these before hitting 1.0 for the go-sdk:
- I think we should hide HostFunction creation behind a function so that we have flexibility of adding new function callbacks in the future
- And I think GuestRuntime is an implementation detail and doesn't need to be public
> refactor: change host function API and hide GuestRuntime

- extism.go
When setting `Manifest.Timeout` I got hung up because it is a `time.Duration` value, so I was setting it to `time.Milliseconds * time.Duration(3000)` instead of just `time.Duration(3000)`. This PR switches `Manifest.Timeout` to be a `uint64` since it is already "timeout in milliseconds" - @mhmd-azeez if you think there's a better fix for this let me know!
> fix: use uint64 for `Manifest.Timeout`

- extism_test.go
- host.go
By default, [Wazero's `api.Memory.Read`](https://github.com/tetratelabs/wazero/blob/103e223d1d0605d0a3ae7089804ae935e302510b/api/wasm.go#L637) returns a *view* of the underlying memory:
> ### Write-through
> 
> This returns a view of the underlying memory, not a copy. This means any
> writes to the slice returned are visible to Wasm, and any updates from
> Wasm are visible reading the returned slice.
> 
> For example:
> 	buf, _ = memory.Read(offset, byteCount)
> 	buf[1] = 'a' // writes through to memory, meaning Wasm code see 'a'.
> 
> If you don't intend-write through, make a copy of the returned slice.
This caused an issue for `varSet` because it basically set the value of the variable to a view of the underlying memory. And before every call, we call `extism_reset` to reset the wasm …
> fix: copy buffers read from wasm memory

- README.md
Something (possibly the LE conversion) was causing a runtime error reading out of bounds when I ran these examples. I don't have time to debug, but figure we're not really losing anything if we just remove these from the example code so they don't fail for other users who are trying the code.
> doc: remove log from example in readme

- extism.go
- extism_test.go
- host.go
- runtime.go
While using the SDK, I found it difficult to use the log level consts and to assign a log level in the plugin configuration struct.
This changes the *LogLevel field to use a non-pointer type, and updates the code accordingly. I think this is ok, since we've define the `iota` 0 value to a `Off` constant. This will be the default / zero-value of the type when left unset in a struct. 
Also, I have prefixed these log level const names with `LogLevel` -- I think it makes it more clear when looking at the name, e.g. `extism.LogLevelInfo` vs. `extism.Info` 
Additionally, although unrelated, this PR includes a couple minor changes to use non-deprecated functions from `io` & `os` packages vs. `ioutil`.
> chore: prefix log level consts, minor package updates

- extism.go
- extism_test.go
- Update main module resolution to match https://github.com/extism/extism/pull/612
- Fix JSON de-serialization of `extism.Manifest` using the `concreteManifest` type (et me know if there is a nicer way to do this in Go)
> cleanup: manifest improvements

- README.md
- extism_test.go
This PR is related to https://github.com/extism/extism/pull/605
```
PS D:\dylibso\go-sdk> go test -benchmem -run=^$ -bench .
goos: windows
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 13th Gen Intel(R) Core(TM) i7-1365U
BenchmarkInitialize/noop-12                         385           3051739 ns/op         2942236 B/op       2751 allocs/op
BenchmarkInitializeWithCache/noop-12                2112            504269 ns/op         1686493 B/op       1554 allocs/op
```
Without using compilation cache: 3ms
with compilation cache: 0.5ms
Since we're already exposing `wazero.RuntimeConfig`, I think we just need to mention it in the README
> feat: compilation cache

- README.md
- extism_test.go
- host.go
Currently we are exposing these wazero APIs:
- [`RuntimeConfig`](https://github.com/tetratelabs/wazero/blob/d39d84505ad8021b5ba47bbc9dd55911b9b0406f/config.go#L40-L171)
- [`ModuleConfig`](https://github.com/tetratelabs/wazero/blob/d39d84505ad8021b5ba47bbc9dd55911b9b0406f/config.go#L444-L638)
- [`api.ValueType`](https://github.com/tetratelabs/wazero/blob/d39d84505ad8021b5ba47bbc9dd55911b9b0406f/api/wasm.go#L83-L110)
- [`api.EncodeXX/api.DecodeXX`](https://github.com/tetratelabs/wazero/blob/d39d84505ad8021b5ba47bbc9dd55911b9b0406f/api/wasm.go#L693-L755)
- [`api.Memory`](https://github.com/tetratelabs/wazero/blob/d39d84505ad8021b5ba47bbc9dd55911b9b0406f/api/wasm.go#L557-L673)
The idea of this PR is hide away wazero from normal usage. If the user doesn't need any advanced configuration or …
> feat: abstract away Wazero's api.ValueType and api.EncodeXX/api.DecodeXX

- README.md
Adds a filesystem access example to `README.md`. 
I'm a little unsure what `__wasm_call_ctors()` and `_initialize()` do and may need a better worded explanation as part of the example. My assumption is that it initializes some needed runtime APIs needed for filesystem access.
Let me know of any adjustments needed.
> Added filesystem access example

- README.md
- extism.go
This PR adds a new method that allows calling plugin functions with a custom context.
This will allow developers to call extism plugins with custom timeouts and cancellation.
> Add plugin.CallWithContext method

- extism.go
- extism_test.go
- host.go
See https://github.com/extism/extism/pull/692
- Breaking: changes the `Memory` field of `Manifest` to a pointer in order to better detect when the memory settings weren't provided
> feat!: add ability to configure size of the Extism var store

- extism.go
- extism_test.go
- host.go
- runtime.go
This PR ensures that the extism plugin struct does not store a context object in itself as this is not idiomatic Go and leads to unexpected behavior. Instead, a context object is passed to each plugin method call that runs a long running operation.
To not break the interface of the SDK, the existing SDK method signatures were preserved, but they were changed to use context.Background under the hood. Next to these, alternative _WithContext methods were added, which allow the caller to provide a custom context object.
> Correctly use context in plugin and provide alternative _WithContext methods

- extism_test.go
- go.mod
- go.sum
Opening this up as a draft for now for discussion. 
This PR brings `wazero` up to the latest version, which introduces their new optimizing compiler. I've added benchmarks from the current version we use `v1.3.0`, and the latest `v1.7.0`:
`v1.3.0`:
```
goos: linux
goarch: amd64
pkg: github.com/extism/go-sdk
cpu: 12th Gen Intel(R) Core(TM) i7-1255U
BenchmarkInitialize/noop-12                  314           3610336 ns/op         2850623 B/op       2744 allocs/op
BenchmarkInitializeWithCache/noop-12                2060            549867 ns/op         1630131 B/op       1554 allocs/op
BenchmarkNoop/noop-12                             245217              4664 ns/op           26216 B/op         22 allocs/op
BenchmarkReplace/8192-12                            5328            249861 ns/op …
```
> chore: bump wazero version

- go.mod
- go.sum
We can wait until the next wazero release to make another release of the go-sdk, but for now using the latest wazero on main will unblock the testing of the python pdk
> chore: pin wazero to main commit for now

- host.go
See https://github.com/extism/extism/pull/743
> cleanup: host takes ownership of memory blocks it gets as arguments

- extism.go
- extism_test.go
- host.go
This fixes a bug where log level is Trace by default and removes PluginConfig.LogLevel since we can't enforce it anymore
> fix: Remove PluginConfig.LogLevel and set default log level to Off

- extism.go
- extism_test.go
- module.go
- runtime.go
This PR does a couple of things:
* It exposes the extism `module` struct.
* It adds methods to get any exported functions from the module.
* It adds a struct to wrap the wazero function definition, allowing Extism to control the API, while also exposing some of the behaviors provided by wazero.
* It removes the `module.wasm` bytes from the `module` struct. It was unused as far as I could tell and I don't see any reason (while it's unused at least) that we wouldn't want the GC to be able to garbage collect that slice, especially when we're dealing with large modules.
> Exposed extism module and added methods to get exported functions

- extism.go
- extism_test.go
- go.mod
- go.sum
- host.go
- plugin.go
- runtime.go
See [Discord thread](https://discord.com/channels/1011124058408112148/1050087851443888138/1298037616838443029).
It seems like there should be a `Plugin` type that is thread-safe, and a `PluginInstance` type that is not thread-safe. The `Plugin `contains the runtime and the compiled module, and you'd have something like `func(p *Plugin) NewInstance() *PluginInstance` which would instantiate a wazero module that would then be used in a single-threaded context.
The idea here is I can compile my plugin one time, and call functions from the module as many times as I want, concurrently, without having to re-compile.
> Support concurrent plugin execution through instances

- extism.go
- plugin.go
This PR allows users to use FS config from `ModuleConfig` (FS is overridden only if Manifest specifies `AllowedPaths`)
> Do not override FS config if no allowed paths are provided

- go.mod
- go.sum
bumps to wazero v1.9.0 which notably includes [an important fix for Go 1.24 compatibility](https://github.com/tetratelabs/wazero/releases/tag/v1.9.0)
> bump: wazero v1.9.0

- README.md
Related to #97
This PR documents `CompiledPlugin`, it also adds a note clarifying the lifetime of a CompiledPlugin is tied to wazero cache if it's enabled
> docs: document compiled plugins
